# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pr:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '59b07b57-79e9-4795-b22f-899890c3b6d3'

   # Web app name
  webAppName: 'petclinic-webapp'

  # Environment name
  environmentName: 'petclinic-webapp'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        # codeCoverageToolOption: 'JaCoCo'
        # codeCoverageRestoreOriginalPomXml: true
        # javaHomeOption: 'JDKVersion'
        # mavenVersionOption: 'Default'
        # mavenAuthenticateFeed: false
        # effectivePomSkip: false
        # sonarQubeRunAnalysis: false

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/surefire-reports/TEST-*.xml'
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployLinuxWebApp
    displayName: Deploy Linux Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: petclinic-webapp'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
    steps:
    - pwsh: |
        $commentUrl = "https://dev.azure.com/syrinechelly/spring-petclinic/_apis/git/repositories/main/pullRequests/$env:PULLREQUESTID/threads?api-version=6.0"
        $body = "{""status"":""active"",""comments"":[{""content"":""hello world"",""parentCommentId"":0,""commentType"":1}]}"
        $headers = @{"Authorization" = "Bearer $env:SYSTEM_ACCESSTOKEN"; "Content-type" = "application/json"}
        Invoke-RestMethod -UrI $commentUrl -Method "POST" -Body $body -Headers $headers
        # curl -X 'PATCH'\
        #  'https://dev.azure.com/syrinechelly/spring-petclinic/_apis/git/repositories/main/pullrequests/$env:PULLREQUESTID?api-version=6.0' 
        #   H 'Authorization: $env:SYSTEM_ACCESSTOKEN'
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        PULLREQUESTID: $(System.PullRequest.PullRequestId)
